"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nq^1s0tc=(%+!re8_kl0-j6_7=i*2xotu(5kbc58pp^o)^q=5a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # To  be changed later during production to the domain name to prevent  cross site scripting attacks


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'newadmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'APP_DIRS':True,


        'DIRS': [
             BASE_DIR / 'app/templates', BASE_DIR / 'newadmin/templates'
         ],     

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    } ,
    # setting  up  mysql database
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shem',
        'USER': 'shem',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '3306',
    } ,

    # setting  up postgresql database
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'shem',
    #     'USER' : 'shem',
    #     'PASSWORD' : '123',
    #     'HOST' : 'localhost',
    #     'PORT' : '5432',
    # } ,

    

} 

# EMAIL SETTINGS
EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 465 
EMAIL_TLS_PORT = 587
EMAIL_HOST_USER = 'afriweb03@gmail.com'
EMAIL_HOST_PASSWORD = 'fvdfylypvsqudjwi'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
# SET EMAIL CONTEXT TO BE SECURE
EMAIL_SSL_CONTEXT = None 




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/' 

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app/static'),
    os.path.join(BASE_DIR, 'newadmin/static'),
]

# Media  Directory setup 
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# MEDIA_FOLDER = 'media'
# MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_FOLDER)
# MEDIA_URL = f'/{MEDIA_FOLDER}/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
